base_url = "https://ilanjoselevich.com"

compile_sass = true

theme = "DeepThought"

generate_feed = true

minify_html = true

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "nord"
render_emoji = true

[extra]

navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL", name = "Home" },
  { url = "$BASE_URL/blog", name = "Blog" },
  { url = "$BASE_URL/CV.pdf", name = "CV" },
 ]},
]

author.name = "Ilan Joselevich"
author.avatar = "/images/avatar.jpg"

social.github = "Kranzes"
social.linkedin = "ilan-joselevich"
social.email = "personal@ilanjoselevich.com"
